"""Streamlit UI for SatyaRepro — Layer 1 static reproducibility audit.

HuggingFace Spaces entry point. Runs seed_check, split_check,
checkpoint_check, and (optionally) dependency_check with no API key.
"""
import asyncio
import json
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import streamlit as st

# Make satyarepro importable when running from the repo root.
sys.path.insert(0, str(Path(__file__).parent))

from satyarepro.tools.layer1 import CheckpointCheck, DependencyCheck, SeedCheck, SplitCheck
from satyarepro.tools.parsers import NotebookParser, ScriptParser

# ── Audit logic ───────────────────────────────────────────────────────────────

async def _audit(tmp_path: Path, requirements_content: str | None) -> list[dict]:
    parser = NotebookParser() if tmp_path.suffix == ".ipynb" else ScriptParser()
    code = await parser.execute(path=str(tmp_path))

    checks: list[tuple[str, object, dict]] = [
        ("seed_check", SeedCheck(), {"code": code}),
        ("split_check", SplitCheck(), {"code": code}),
        ("checkpoint_check", CheckpointCheck(), {"code": code}),
    ]
    if requirements_content is not None:
        checks.append(
            ("dependency_check", DependencyCheck(), {"requirements": requirements_content})
        )

    results = []
    for name, tool, kwargs in checks:
        raw = await tool.execute(**kwargs)
        results.append({"name": name, "result": json.loads(raw)})
    return results


def _run_audit(uploaded_file, requirements_content: str | None) -> list[dict]:
    suffix = Path(uploaded_file.name).suffix
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(uploaded_file.getvalue())
        tmp_path = Path(tmp.name)
    try:
        return asyncio.run(_audit(tmp_path, requirements_content))
    finally:
        tmp_path.unlink(missing_ok=True)


# ── Report formatting ─────────────────────────────────────────────────────────

_LABELS = {
    "seed_check": "Random seed fixation",
    "split_check": "Train/test data leakage",
    "checkpoint_check": "Model checkpoint saving",
    "dependency_check": "Dependency version pins",
}

_DESCRIPTIONS = {
    "seed_check": "Checks that NumPy, PyTorch, TensorFlow, and Python random are seeded.",
    "split_check": "Detects preprocessing fitted on the full dataset instead of training data.",
    "checkpoint_check": "Verifies that trained models are saved to disk.",
    "dependency_check": "Flags packages without pinned versions in requirements.txt.",
}


def _format_check_text(name: str, result: dict) -> str:
    status = result.get("status", "unknown")
    icon = "PASS" if status == "ok" else ("FAIL" if status == "issues_found" else "WARN")
    label = _LABELS.get(name, name)
    lines = [f"[{icon}]  {label}"]

    if "message" in result and status == "ok":
        lines.append(f"       {result['message']}")
    if "error" in result:
        lines.append(f"       error: {result['error']}")
    for issue in result.get("issues", []):
        if isinstance(issue, dict):
            line_no = issue.get("line", "?")
            msg = issue.get("warning") or issue.get("call", str(issue))
            lines.append(f"       line {line_no}: {msg}")
        else:
            lines.append(f"       {issue}")
    if "recommendation" in result:
        lines.append(f"       → {result['recommendation']}")
    for pkg in result.get("unpinned_packages", []):
        lines.append(f"       unpinned: {pkg}")
    return "\n".join(lines)


def _build_report(filename: str, checks: list[dict]) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    passed = sum(1 for c in checks if c["result"].get("status") == "ok")
    total = len(checks)
    lines = [
        "=" * 60,
        "  SatyaRepro — Static Reproducibility Audit",
        f"  File:    {filename}",
        f"  Date:    {ts}",
        f"  Result:  {passed}/{total} checks passed",
        "=" * 60,
        "",
    ]
    for check in checks:
        lines.append(_format_check_text(check["name"], check["result"]))
        lines.append("")
    lines += [
        "-" * 60,
        "Generated by SatyaRepro (https://github.com/your-org/satyarepro)",
        "University of Michigan MIDAS · NIH DAIR3 (5R25GM151182-03)",
    ]
    return "\n".join(lines)


# ── Page ──────────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="SatyaRepro — Reproducibility Auditor",
    page_icon="🔬",
    layout="centered",
)

st.title("🔬 SatyaRepro")
st.markdown(
    "**Static reproducibility auditor for biomedical AI/ML workflows.**  \n"
    "Upload a Jupyter notebook or Python script — no API key required."
)

st.divider()

col_code, col_reqs = st.columns([3, 2])
with col_code:
    uploaded_file = st.file_uploader(
        "Notebook or script",
        type=["ipynb", "py"],
        help="Accepts .ipynb (Jupyter notebook) or .py (Python script).",
    )
with col_reqs:
    requirements_file = st.file_uploader(
        "requirements.txt (optional)",
        type=["txt"],
        help="Upload to check for unpinned dependency versions.",
    )

requirements_content: str | None = None
if requirements_file is not None:
    requirements_content = requirements_file.getvalue().decode("utf-8")

if uploaded_file is None:
    st.info("Upload a file above to begin the audit.")
    st.markdown(
        "---\n"
        "*SatyaRepro · University of Michigan MIDAS · NIH DAIR3 (5R25GM151182-03)*"
    )
    st.stop()

with st.spinner(f"Auditing **{uploaded_file.name}**…"):
    try:
        checks = _run_audit(uploaded_file, requirements_content)
    except Exception as exc:
        st.error(f"Audit failed: {exc}")
        st.stop()

st.divider()
st.subheader("Results")

passed = sum(1 for c in checks if c["result"].get("status") == "ok")
total = len(checks)

if passed == total:
    st.success(f"All {total} checks passed.")
elif passed == 0:
    st.error(f"All {total} checks found issues.")
else:
    issues_count = total - passed
    st.warning(f"{issues_count} of {total} checks found issues.")

for check in checks:
    name = check["name"]
    result = check["result"]
    status = result.get("status", "unknown")
    icon = "✅" if status == "ok" else ("❌" if status == "issues_found" else "⚠️")
    label = _LABELS.get(name, name)
    desc = _DESCRIPTIONS.get(name, "")

    with st.expander(f"{icon}  {label}", expanded=(status != "ok")):
        if desc:
            st.caption(desc)

        if status == "ok":
            st.success(result.get("message", "No issues found."))

        if "error" in result:
            st.error(result["error"])

        issues = result.get("issues", [])
        if issues:
            for issue in issues:
                if isinstance(issue, dict):
                    line_no = issue.get("line", "?")
                    msg = issue.get("warning") or issue.get("call", str(issue))
                    st.markdown(f"- **Line {line_no}:** {msg}")
                else:
                    st.markdown(f"- {issue}")

        unpinned = result.get("unpinned_packages", [])
        if unpinned:
            st.markdown(f"**{len(unpinned)} unpinned package(s):**")
            st.code("  ".join(unpinned), language=None)

        if "recommendation" in result:
            st.info(result["recommendation"])

        detected = result.get("frameworks_detected", [])
        seeded = result.get("seeded", [])
        if detected:
            st.caption(
                f"Frameworks detected: {', '.join(detected)}"
                + (f" | Seeded: {', '.join(seeded)}" if seeded else " | None seeded")
            )

st.divider()
report_text = _build_report(uploaded_file.name, checks)
st.download_button(
    label="⬇ Download audit report (.txt)",
    data=report_text,
    file_name=f"satyarepro_{Path(uploaded_file.name).stem}_audit.txt",
    mime="text/plain",
)

st.markdown(
    "---\n"
    "*SatyaRepro · University of Michigan MIDAS · NIH DAIR3 (5R25GM151182-03)*"
)
