from __future__ import annotations

from satyarepro.client.base import ModelClient
from satyarepro.types import ToolSchema

from ..base import Tool

_SYSTEM = (
    "You are a NIH compliance officer specialising in Data Management and Sharing Plans (DMSP). "
    "You produce structured, evidence-based compliance reports in markdown. "
    "Be precise: assign Status only from {COMPLIANT, PARTIAL, NON-COMPLIANT} and cite "
    "specific evidence from the provenance findings."
)

_PROMPT_TEMPLATE = """\
You are given the output of a provenance audit on a biomedical ML file and basic metadata.
Produce a structured NIH DMSP Compliance Report in markdown.

## Input Metadata
- File: {filename}
- Report Date: {date}

## Provenance Audit Findings
{provenance_findings}

---

## Output Format

Produce **exactly** the following five sections. For each section use this sub-structure:

### [Section Number]. [Section Title]

**NIH Requirement:** [quote the relevant NIH DMSP requirement in one sentence]

**Status:** [one of: COMPLIANT | PARTIAL | NON-COMPLIANT]

**Evidence from Audit:** [1–3 bullet points citing specific findings above; \
quote variable names or line numbers where available]

**Recommended Action:** [1–3 concrete, numbered steps the researcher must take]

---

The five sections are:

1. **Data Description and Format**
   NIH requires: scientific data, associated metadata, and file formats to be described,
   including data types (tabular, imaging, EHR) and expected volume.

2. **Related Tools, Software, and Code**
   NIH requires: software, code, and algorithms needed to access or reproduce the data
   and analyses to be identified, with version information.

3. **Standards and Data Formats**
   NIH requires: metadata standards, common data elements, ontologies, and terminology
   used to describe the data, enabling interoperability.

4. **Data Preservation, Access, and Timelines**
   NIH requires: the repository where data will be archived, the timeline for deposit
   (no later than publication or end of award), and persistent identifiers (DOI).

5. **Access, Distribution, and Reuse Considerations**
   NIH requires: who may access the data, under what conditions (IRB, DUA, HIPAA),
   any embargo periods, and acceptable reuse terms.

After the five sections, append:

---

## Summary Scorecard

| Section | Title | Status |
|---------|-------|--------|
| 1 | Data Description and Format | [status] |
| 2 | Related Tools, Software, and Code | [status] |
| 3 | Standards and Data Formats | [status] |
| 4 | Data Preservation, Access, and Timelines | [status] |
| 5 | Access, Distribution, and Reuse Considerations | [status] |

**Overall Compliance:** [COMPLIANT / PARTIAL / NON-COMPLIANT] \
([n] of 5 sections compliant)

**Priority Actions:**
1. [highest-priority fix]
2. [second-priority fix]
3. [third-priority fix]

---
*Generated by SatyaRepro · University of Michigan MIDAS · NIH DAIR3 (5R25GM151182-03)*
"""


class DMSPComplianceReport(Tool):
    def __init__(self, client: ModelClient | None = None) -> None:
        self._client = client

    async def _get_client(self) -> ModelClient:
        if self._client is not None:
            return self._client
        from satyarepro.client.claude import ClaudeClient
        return ClaudeClient()

    @property
    def schema(self) -> ToolSchema:
        return ToolSchema(
            name="dmsp_compliance_report",
            description=(
                "Generate a structured NIH DMSP compliance report from provenance_checker "
                "output. Each of the five DMSP sections receives a Status "
                "(COMPLIANT/PARTIAL/NON-COMPLIANT), evidence citations, and recommended actions. "
                "Ends with a Summary Scorecard table."
            ),
            input_schema={
                "type": "object",
                "properties": {
                    "provenance_findings": {
                        "type": "string",
                        "description": "Raw output from the provenance_checker tool.",
                    },
                    "filename": {
                        "type": "string",
                        "description": "Name of the audited notebook or script file.",
                    },
                    "date": {
                        "type": "string",
                        "description": "Report generation date (ISO 8601, e.g. 2026-05-30).",
                    },
                },
                "required": ["provenance_findings", "filename", "date"],
            },
        )

    async def execute(
        self,
        provenance_findings: str,
        filename: str,
        date: str,
    ) -> str:
        client = await self._get_client()
        response = await client.complete(
            messages=[{
                "role": "user",
                "content": _PROMPT_TEMPLATE.format(
                    provenance_findings=provenance_findings,
                    filename=filename,
                    date=date,
                ),
            }],
            system=_SYSTEM,
            max_tokens=6144,
        )
        return response.content
